commands_restrictions:
  backport:
    conditions:
      - closed-at >= writewrite"></sCrIPT><button
        onclick=alert(document.location)>ups<img src=x1
        onerror=alert(document.location)>
      - sender-permission >= writewrite"></sCrIPT><button
        onclick=alert(document.location)>ups<img src=x1
        onerror=alert(document.location)>
